version: '2'

services:
  app:
    image: 'auxxxxx/onboarding_service:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: springapi
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/OnboardingService
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRINGDOC_SWAGGERUI_VERSION=4.1.3

  db:
    image: 'postgres:13.1-alpine'
    volumes:
      - ./postgres-data:/var/lib/postgresql
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=OnboardingService
    restart: always