server:
  port: 8080
springdoc:
  swagger-ui:
    version: 4.1.3

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OnboardingService
    username: postgres
    password: "%Eo434Xd"
  #jpa.hibernate.ddl-auto: update
  jpa.hibernate.ddl-auto: create

storage:
  root: "glasflair-media-assets"
  credentials:
    key: "YCAJEtSkeatkzSy8Ku-CAt7VV"
    secret: "YCP438_siyUDOQJawDdYq7S2JgSIGRtfnbOU-cHT"
  baseUrl: "https://storage.yandexcloud.net/glasflair-media-assets/"

manager-credentials:
  email: "onboarding.manager01@gmail.com"
  password: "h#934@fhP0%h8*Ay#"

security:
  secret: "24432646294A404E635266556A586E3272357538782F413F442A472D4B615064"